include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    must_be_immutable: ignore
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    prefer_typing_uninitialized_variables: ignore
